import hashlib, os, re, sys

src, outdir = sys.argv[1], sys.argv[2]
MARKER = "# wekatester-layout: generated"
NAME = "000-wekatester-layout.job"
# One namespace collects CONTRIBUTORS -- each source job's own geometry.
# Emitting one section per (pruned) contributor lays out exactly the union of
# files the jobs will open. A single independent-max section (max numjobs x
# max nrfiles x max filesize) would instead create the full cross-product
# grid, over-provisioning disk by integer factors whenever the geometries
# diverge -- and the capacity guard would never see it coming.
namespaces = {}   # key -> dict(section, fmt, contribs=[{numjobs,nrfiles,size_b,fs,sz}])
engines = {}
directory = ""
for f in sorted(os.listdir(src)):
    if not re.match(r"^[0-9]", f): continue
    path = os.path.join(src, f)
    if not os.path.isfile(path): continue
    lines = open(path).read().splitlines()
    if f == NAME or any(l.startswith(MARKER) for l in lines[:3]):
        continue   # never derive layout from layout
    fmt = first_value(lines, "filename_format")
    if fmt:
        key, section, out_fmt = fmt, None, fmt
    else:
        # No filename_format: fio's default naming embeds the job section
        # name, so the layout section must carry the SAME name as the file's
        # measured (last) section or it would create differently-named files.
        sec = last_section(lines) or f
        key, section, out_fmt = f"__jobname__:{sec}", sec, ""
    eng = first_value(lines, "ioengine")
    if eng: engines[eng] = engines.get(eng, 0) + 1
    directory = directory or first_value(lines, "directory")
    fs, size = first_value(lines, "filesize"), first_value(lines, "size")
    size_b = -1
    for v in (fs, size):
        if v:
            try: size_b = max(size_b, parse_size(v))
            except ValueError: pass   # e.g. size=50%: not derivable
    ns = namespaces.setdefault(key, {"section": section, "fmt": out_fmt, "contribs": []})
    ns["contribs"].append({"numjobs": int(first_value(lines, "numjobs") or 1),
                           "nrfiles": int(first_value(lines, "nrfiles") or 1),
                           "size_b": size_b, "fs": fs, "sz": size})

if not namespaces:
    sys.exit(f"ERROR: no jobfiles to derive a layout from in {src}")

def prune(contribs):
    """Keep only contributors no kept contributor's grid fully covers.
    Descending order makes it one pass: a duplicate or dominated entry always
    meets its dominator first."""
    kept = []
    for a in sorted(contribs, key=lambda c: (-c["numjobs"], -c["nrfiles"], -c["size_b"])):
        if not any(a["numjobs"] <= b["numjobs"] and a["nrfiles"] <= b["nrfiles"]
                   and a["size_b"] <= b["size_b"] for b in kept):
            kept.append(a)
    return kept

body = []
body.append("# Auto-generated by wekatester: lays out every file the set's jobs")
body.append("# will use, as the first job of the run -- a cross-client barrier, so")
body.append("# all files exist on all machines before any measured test starts.")
body.append("# Edit freely: an edited layout job is preserved (regenerate with -g).")
body.append("[global]")
body.append(f"directory={directory or '/mnt/weka'}")
# fallocate=none is what makes the layout sweep's size test sound. fio
# defaults to fallocate=native on Linux, which gives a file its full
# st_size instantly and only then writes the data -- so a layout killed
# part way leaves a full-size file full of zeros, which the sweep credits
# as complete and never rewrites. Without preallocation an interrupted
# create leaves a SHORT file, which the sweep deletes and recreates.
body.append("fallocate=none")
body.append("create_serialize=0")
best_engine = pick_engine(engines)
body.append(f"ioengine={best_engine}")
n = 0
for key in sorted(namespaces):
    ns = namespaces[key]
    kept = prune(ns["contribs"])
    prev = None
    for c in kept:
        n += 1
        # A jobname namespace (no filename_format) names its files after the
        # section, so a lone contributor keeps that name; several need
        # distinct names for wait_for, so fio's default naming
        # ($jobname.$jobnum.$filenum) is reproduced explicitly instead.
        if ns["section"] and len(kept) == 1:
            sec, fmt = ns["section"], ns["fmt"]
        elif ns["section"]:
            sec, fmt = "layout-%d" % n, f"{ns['section']}.$jobnum.$filenum"
        else:
            sec, fmt = "layout-%d" % n, ns["fmt"]
        body.append("")
        body.append(f"[{sec}]")
        # Contributors of one namespace have overlapping grids and must not
        # lay out the same file concurrently (fio's extend can unlink a file
        # another section is mid-write on), so they chain via wait_for.
        # Distinct namespaces touch disjoint files: those sections run in
        # parallel -- a global stonewall here would only slow the layout.
        if prev: body.append(f"wait_for={prev}")
        prev = sec
        body.append("create_only=1")
        body.append("blocksize=1Mi")
        if fmt: body.append(f"filename_format={fmt}")
        if c["fs"]: body.append(f"filesize={c['fs']}")
        elif c["sz"]: body.append(f"size={c['sz']}")
        else: body.append(f"# WARNING: no derivable file size in this namespace ({key})")
        if c["nrfiles"] > 1: body.append(f"nrfiles={c['nrfiles']}")
        body.append(f"numjobs={c['numjobs']}")

normalized = "\n".join(l.rstrip() for l in body)
digest = hashlib.sha256(normalized.encode()).hexdigest()
os.makedirs(outdir, exist_ok=True)
with open(os.path.join(outdir, NAME), "w") as fp:
    fp.write(f"{MARKER} sha256={digest}\n" + normalized + "\n")
print(f"layout: generated {os.path.join(outdir, NAME)} ({len(namespaces)} namespace(s))")
