# the next line tells wekatester to report only bandwidth.
# report bandwidth 
[global]
filesize=100M
time_based=1
startdelay=5
exitall_on_error=1
create_serialize=0
filename_format=$jobname/$jobnum/$filenum
directory=/mnt/wekatester
group_reporting=1
clocksource=gettimeofday
runtime=30
ioengine=posixaio
disk_util=0
direct=1

[fio-bandwidthSW-00]
description='wekatester Sequential Write bandwidth workload'
blocksize=1Mi
rw=write
numjobs=32
iodepth=1
