# the next line tells wekatester to report only iops, bandwidt or latency.
# report iops
[global]
filesize=100M
time_based=1
startdelay=5
exitall_on_error=1
create_serialize=0
filename_format=$filenum/$jobnum
directory=/mnt/wekatester
group_reporting=1
clocksource=gettimeofday
runtime=30
ioengine=posixaio
disk_util=0
direct=1

[fio-iopsR-00]
description='wekatester Read iops workload'
numjobs=192
bs=4k
rw=randread
