# the next line tells to report only iops, bandwidth or latency.
# report iops
[global]
filesize=20G
time_based=1
startdelay=5
exitall_on_error=1
create_serialize=0
filename_format=$filenum/$jobnum
directory=/mnt/wekatester
group_reporting=1
clocksource=gettimeofday
runtime=30
ioengine=posixaio
disk_util=0
direct=1

[fio-createfiles-00]
description='pre-create files'
create_only=1
numjobs=192

[fio-iopsR-00]
stonewall
description='Read iops workload'
numjobs=192
bs=4k
rw=randread
