BEGIN {
    lay_reset(); directory = ""
    for (a = 2; a < ARGC; a++) {
        f = ARGV[a]; sub(/.*\//, "", f)
        if ((n = readlines(ARGV[a], L)) < 0) awk_fail("cannot read " ARGV[a])
        if (f == layout_job() || is_layout_marked(L, n)) continue   # never derive layout from layout
        lay_add(L, n, f, ARGV[a]); lay_engine(L, n)
        if (directory == "") directory = first_value(L, n, "directory")
    }
    if (!LAY_NNS) awk_fail("no jobfiles to derive a layout from in " ARGV[1])
    nb = 0
    B[++nb] = "# Auto-generated by wekatester: lays out every file the set\047s jobs"
    B[++nb] = "# will use, as the first job of the run -- a cross-client barrier, so"
    B[++nb] = "# all files exist on all machines before any measured test starts."
    B[++nb] = "# Edit freely: an edited layout job is preserved (regenerate with -g)."
    B[++nb] = "[global]"
    B[++nb] = "directory=" (directory != "" ? directory : "/mnt/weka")
    # fallocate=none makes the sweep size test sound: native preallocation
    # gives a killed layout full-size files of zeros, credited as complete
    # (README).
    B[++nb] = "fallocate=none"
    B[++nb] = "create_serialize=0"
    B[++nb] = "ioengine=" pick_engine(LAY_TALLY, LAY_EORD, LAY_NE)
    nb = lay_sections(B, nb)
    print LAY_NNS
    for (i = 1; i <= nb; i++) print rstrip(B[i])
}
